from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any
class BrokerProvider(ABC):
    @abstractmethod
    async def enqueue(self, payload: dict[str, Any], priority: str = "default") -> None: ...
    @abstractmethod
    async def dequeue(self) -> dict[str, Any] | None: ...
    @abstractmethod
    async def ack(self, job_id: str) -> None: ...
    @abstractmethod
    async def nack(self, payload: dict[str, Any]) -> None: ...
