from __future__ import annotations
from abc import ABC, abstractmethod
from typing import Any
class TransportProvider(ABC):
    @abstractmethod
    async def start(self) -> None: ...
    @abstractmethod
    async def stop(self) -> None: ...
    @abstractmethod
    async def send(self, payload: dict[str, Any]) -> None: ...
    @abstractmethod
    async def receive(self) -> dict[str, Any] | None: ...
    @abstractmethod
    async def close(self) -> None: ...
